/*
 * Auto-generated by RDF4JSchemaGenerator
 */
<#if packageName??>
package ${packageName};

</#if>
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;

/**
 * ${title!"No title found"}
<#if description??>
 * ${description!""}
</#if>
 *
 * Namespace ${name}
 * Prefix: {@code <${prefix}>}
 *
<#list seeAlsoUrls as seeAlsoUrl>
 * @see <a href="${seeAlsoUrl}>${seeAlsoUrl}</a>
</#list>
 */
public class ${className} {

    /**
     * {@code <${prefix}>}
     */
    public static final String NAMESPACE = "${prefix}"; 

    /**
     * {@code <${name}>}
     */
    public static final String PREFIX = "${name}"; 

<#if stringConstants??>
    /**********************
     * IRI String Constants
     **********************/
<#list stringConstants as stringConstant>
    /**
<#if stringConstant.getLabel().isPresent()>
     * ${stringConstant.getLabel().get()}
</#if>
     */
</#list>
</#if>

<#if localNameStringConstants??>
    /*****************************
     * Local Name String Constants
     *****************************/
<#list localNameStringConstants as localNameStringConstant>
    /**
     * ${localNameStringConstant.IRI}
     */
</#list>
</#if>

<#if iriConstants??>
    /***************
     * IRI Constants
     ***************/
<#list iriConstants as iriConstant>
    /**
<#if iriConstant.getLabel().isPresent()>
     * ${iriConstant.getLabel().get().stringValue()?js_string}
     * <p>
</#if>
     * {@code ${iriConstant.getIRI().stringValue()?js_string}}
<#if iriConstant.getDescription().isPresent()>
     * <p>
     * ${iriConstant.getDescription().get().stringValue()?js_string}
</#if>
     * @see <a href="${iriConstant.getIRI().stringValue()?js_string}}">${iriConstant.getRawRecordKey()?js_string}</a>
     */
     public static final IRI ${iriConstant.getFormattedRecordKey()};
</#list>
</#if>

    /**
     * Static initializer
     */
    static {
        ValueFactory vf = SimpleValueFactory.getInstance();
<#if iriConstants??>
        /***************
         * IRI Constants
         ***************/
<#list iriConstants as iriConstant>
        ${iriConstant.getFormattedRecordKey()} = vf.createIRI("${iriConstant.getIRI().stringValue()?j_string}");
</#list>
</#if>
    }
    
    private ${className}() {
        // static access only
    }
}