<#macro escapeAndWrapLine rawString><#assign escapedDescription = rawString?js_string>
${WordUtils.wrap(escapedDescription, 70, "\n" + StringUtils.repeat(" ", 4) + " * ", false)}</#macro>
<#macro schemaRecordJavadoc schemaRecord>
    /**
<#if schemaRecord.getLabel().isPresent()>
     * <@escapeAndWrapLine rawString="${schemaRecord.getLabel().get().stringValue()}"/>
     * <p>
</#if>
     * {@code ${schemaRecord.getIRI().stringValue()?js_string}}
<#if schemaRecord.getDescription().isPresent()>
     * <p>
     * <@escapeAndWrapLine rawString="${schemaRecord.getDescription().get().stringValue()}"/>
</#if>
     * @see <a href="${schemaRecord.getIRI().stringValue()?js_string}}">${schemaRecord.getRawRecordKey()?js_string}</a>
     */
</#macro>
/*
 * Auto-generated by RDF4JSchemaGenerator
 */
<#if packageName??>
package ${packageName};

</#if>
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;

/**
 * ${title!"No title found"}
<#if description??>
 * ${description!""}
</#if>
 *
 * Namespace ${name}
 * Prefix: {@code <${prefix}>}
 *
<#list seeAlsoUrls as seeAlsoUrl>
 * @see <a href="${seeAlsoUrl}>${seeAlsoUrl}</a>
</#list>
 */
public class ${className} {

    /**
     * {@code <${prefix}>}
     */
    public static final String NAMESPACE = "${prefix}"; 

    /**
     * {@code <${name}>}
     */
    public static final String PREFIX = "${name}"; 

<#if stringConstants??>
    /**********************
     * IRI String Constants
     **********************/
<#list stringConstants as stringConstant>

    <@schemaRecordJavadoc schemaRecord=stringConstant />
    public static final String ${stringConstant.getFormattedRecordKey()} = "${stringConstant.getRawRecordKey()}";
</#list>
</#if>

<#if localNameStringConstants??>
    /*****************************
     * Local Name String Constants
     *****************************/
<#list localNameStringConstants as localNameStringConstant>

    <@schemaRecordJavadoc schemaRecord=localNameStringConstant />
    public static final String ${localNameStringConstant.getFormattedRecordKey()} = "${localNameStringConstant.getRawRecordKey()}";
</#list>
</#if>

<#if iriConstants??>
    /***************
     * IRI Constants
     ***************/
<#list iriConstants as iriConstant>

    <@schemaRecordJavadoc schemaRecord=iriConstant />
    public static final IRI ${iriConstant.getFormattedRecordKey()};
</#list>
</#if>

    /**
     * Static initializer
     */
    static {
        ValueFactory vf = SimpleValueFactory.getInstance();
<#if iriConstants??>
        /***********************
         * IRI Constant creation
         ***********************/
<#list iriConstants as iriConstant>
        ${iriConstant.getFormattedRecordKey()} = vf.createIRI("${iriConstant.getIRI().stringValue()?j_string}");
</#list>
</#if>
    }
    
    private ${className}() {
        // static access only
    }
}