#!/bin/bash
# This script runs the RDF4J Schema Generator code.
#
# Before running this script for the first time
# you may need to run:
#     chmod +x rdf4j-schema-generator
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -d "${DIR}/cli/target/appassembler/bin" ]; then
    (cd ${DIR} && mvn -quiet clean install -DskipTests)
fi

chmod u+x `ls ${DIR}/cli/target/appassembler/bin/*`
$DIR/cli/target/appassembler/bin/rdf4j-schema-generator "$@"
