#!/bin/bash
# This script runs the Sesame Vocab Builder code.
# Before running this script for the first time 
# you may need to run:
#     chmod +x sesame-vocab-builder
#

if [ ! -d "sesame-vocab-builder-cli/target/appassembler/bin" ]; then
    mvn -quiet clean install
fi

chmod u+x sesame-vocab-builder-cli/target/appassembler/bin/*
sesame-vocab-builder-cli/target/appassembler/bin/sesame-vocab-builder
