#!/bin/bash
# This script runs the Sesame Vocab Builder code.
#
# Before running this script for the first time
# you may need to run:
#     chmod +x sesame-vocab-builder
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -d "${DIR}/vocab-builder-cli/target/appassembler/bin" ]; then
    (cd ${DIR} && mvn -quiet clean install -DskipTests)
fi

chmod u+x `ls ${DIR}/vocab-builder-cli/target/appassembler/bin/*`
$DIR/vocab-builder-cli/target/appassembler/bin/sesame-vocab-builder "$@"
